package GUI;

import civitasv2.CivitasJuego;
import civitasv2.Diario;
import civitasv2.Jugador;
import civitasv2.OperacionInmobiliaria;
import civitasv2.OperacionJuego;
import controladorCivitas.Respuesta;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author migue8gl
 */
public class CivitasView extends javax.swing.JFrame implements Vista {

    CivitasJuego juego;

    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
    }

    public void setCivitasJuego(CivitasJuego juego) {
        this.juego = juego;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jugadorPanel1 = new GUI.JugadorPanel();
        Casilla = new javax.swing.JLabel();
        casilla = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sigOperacion = new javax.swing.JTextField();
        Ranking = new javax.swing.JLabel();
        ranking = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        titulo.setText("CivitasView");
        getContentPane().add(titulo);
        getContentPane().add(jugadorPanel1);

        Casilla.setText("Casilla");
        getContentPane().add(Casilla);

        casilla.setEditable(false);
        casilla.setText("casilla");
        casilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casillaActionPerformed(evt);
            }
        });
        getContentPane().add(casilla);

        jLabel1.setText("SiguienteOperacion");
        getContentPane().add(jLabel1);

        sigOperacion.setText("sigOperacion");
        sigOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigOperacionActionPerformed(evt);
            }
        });
        getContentPane().add(sigOperacion);

        Ranking.setText("Ranking");
        getContentPane().add(Ranking);

        ranking.setEditable(false);
        ranking.setText("ranking");
        ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingActionPerformed(evt);
            }
        });
        getContentPane().add(ranking);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casillaActionPerformed

    private void sigOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sigOperacionActionPerformed

    private void rankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Casilla;
    private javax.swing.JLabel Ranking;
    private javax.swing.JTextField casilla;
    private javax.swing.JLabel jLabel1;
    private GUI.JugadorPanel jugadorPanel1;
    private javax.swing.JTextField ranking;
    private javax.swing.JTextField sigOperacion;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualiza() {
        jugadorPanel1.setJugador(this.juego.getJugadorActual());
        casilla.setText(this.juego.getCasillaActual().toString());
        Ranking.setVisible(false);
        ranking.setVisible(false);

        if (this.juego.finalDelJuego()) {
            ranking.setVisible(true);
            Ranking.setVisible(true);
            String cadena = "";
            ArrayList<Jugador> jugadores = this.juego.ranking();
            int i = 0;
            for (Jugador jugador : jugadores) {
                if (i == 0) {
                    cadena += jugador.toString();
                } else {
                    cadena += "\n" + jugador.toString();
                }
                i++;
            }
            ranking.setText(cadena);
        }
        repaint();
        revalidate();
    }

    @Override
    public void pausa() {
        int val = JOptionPane.showConfirmDialog(null, "¿Continuar?",
                "Siguiente paso", JOptionPane.YES_NO_OPTION);
        if (val == 1) {
            System.exit(0);
        }
    }

    @Override
    public Respuesta comprar() {
        int opcion = 1 - JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", "Compra", JOptionPane.YES_NO_OPTION);
        if (opcion == 0) {
            return Respuesta.NO;
        } else {
            return Respuesta.SI;
        }
    }

    @Override
    public OperacionInmobiliaria elegirOperacion() {
        GestionarDialog dialog = new GestionarDialog(this);
        return OperacionInmobiliaria.values()[dialog.getGestion()];
    }

    @Override
    public int elegirPropiedad() {
        PropiedadDialog dialog = new PropiedadDialog(this, juego.getJugadorActual());
        return dialog.getPropiedadElegida();
    }

    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operacion) {
        sigOperacion.setText(operacion.toString());
        if (operacion == OperacionJuego.AVANZAR) {
            Dado.createInstance(this);
            repaint();
        }

    }

    @Override
    public void mostrarEventos() {
        if (!Diario.getInstance().getEventos().isEmpty()) {
            DiarioDialog diarioD = new DiarioDialog(this); //crea la ventana del diario
        }
    }
}
