/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitasv2.CasillaCalle;
import civitasv2.Jugador;
import java.util.ArrayList;

/**
 *
 * @author migue8gl
 */
public class JugadorPanel extends javax.swing.JPanel {

    private Jugador jugador;

    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
        esp.setText(Boolean.toString(this.jugador.esEspeculador()));
        nomb.setText(this.jugador.getNombre());
        sald.setText(Float.toString(this.jugador.getSaldo()));

        rellenaPropiedades(this.jugador.getPropiedades());

        repaint();
        revalidate();
    }

    private void rellenaPropiedades(ArrayList<CasillaCalle> lista) {
        // Se elimina la información antigua
        propiedadesPanel.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for (CasillaCalle t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        salgo = new javax.swing.JLabel();
        especulador = new javax.swing.JLabel();
        nomb = new javax.swing.JTextField();
        sald = new javax.swing.JTextField();
        esp = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        nombre.setText("Nombre");
        add(nombre);

        salgo.setText("Saldo");
        add(salgo);

        especulador.setText("Especulador");
        add(especulador);

        nomb.setEditable(false);
        nomb.setText("nombre");
        nomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombActionPerformed(evt);
            }
        });
        add(nomb);

        sald.setEditable(false);
        sald.setText("saldo");
        add(sald);

        esp.setEditable(false);
        esp.setText("especulador");
        add(esp);
        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void nombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField esp;
    private javax.swing.JLabel especulador;
    private javax.swing.JTextField nomb;
    private javax.swing.JLabel nombre;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JTextField sald;
    private javax.swing.JLabel salgo;
    // End of variables declaration//GEN-END:variables

}
